apiVersion: v1
kind: Secret
metadata:
  name: kafka-exporter-secrets
  namespace: microservices
type: Opaque
data:
  kafka-exporter-key.pem: $(cat kafka-exporter-key.pem.b64)
  kafka-exporter-certificate.pem: $(cat kafka-exporter-certificate.pem.b64)
  ca-cert.pem: $(cat ca-cert.pem.b64)
