apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-exporter
  namespace: microservices
  labels:
    app: zookeeper-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-exporter
  template:
    metadata:
      labels:
        app: zookeeper-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9141'
    spec:
      containers:
      - name: zookeeper-exporter
        image: dabealu/zookeeper-exporter:latest
        env:
        - name: ZK_SERVER
          value: "zookeeper.microservices.svc.cluster.local:2181"
        ports:
        - containerPort: 9141
          name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-exporter
  namespace: microservices
  labels:
    app: zookeeper-exporter
spec:
  ports:
  - port: 9141
    targetPort: metrics
    name: metrics
  selector:
    app: zookeeper-exporter
