apiVersion: v1
kind: Secret
metadata:
  name: orders-service-kafka-secrets
  namespace: microservices
type: Opaque
data:
  orders-service-key.pem: $(cat orders-service-key.pem.b64)
  orders-service-certificate.pem: $(cat orders-service-certificate.pem.b64)
  ca-cert.pem: $(cat ca-cert.pem.b64)
