apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
  namespace: microservices
type: Opaque
data:
  kafka.server.keystore.jks: $(cat kafka.server.keystore.jks.b64)
  kafka.server.truststore.jks: $(cat kafka.server.truststore.jks.b64)
  ca-cert.pem: $(cat ca-cert.pem.b64)
