apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-ingress
  namespace: microservices
spec:
  podSelector:
    matchLabels:
      app: prometheus
  ingress:
  - {}  # Empty rule = allow ALL ingress
  policyTypes:
    - Ingress
