apiVersion: v1
kind: Secret
metadata:
  name: mongodb-users-secrets
  namespace: microservices
type: Opaque
stringData:
  username: admin
  password: "MongoDBUserPass123!"  # CHANGE THIS to a strong password
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-inventory-secrets
  namespace: microservices
type: Opaque
stringData:
  username: admin
  password: "MongoDBInventoryPass123!"  # CHANGE THIS to a strong password
