apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh', '-c', 'until nc -z mongo-users.microservices.svc.cluster.local 27017; do echo waiting for mongo-users; sleep 10; done']
        - name: wait-for-kafka
          image: busybox
          command: ['sh', '-c', 'until nc -z kafka-cluster 9092; do echo waiting for kafka; sleep 10; done']
      containers:
        - name: users-service
          image: youzarsif99/microservice-project_users-service:v1 # your-repository-name/microservice-project_users
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              value: mongodb://mongo-users:27017/users_db
            - name: KAFKA_BROKER
              value: kafka-cluster:9092
          volumeMounts:
            - name: kafka-client-secrets
              mountPath: /etc/kafka/secrets/ca-cert.pem
              subPath: ca-cert.pem
              readOnly: true
            - name: kafka-client-secrets
              mountPath: /etc/kafka/secrets/users-service-key.pem
              subPath: users-service-key.pem
              readOnly: true
            - name: kafka-client-secrets
              mountPath: /etc/kafka/secrets/users-service-certificate.pem
              subPath: users-service-certificate.pem
              readOnly: true
      volumes:
        - name: kafka-client-secrets
          secret:
            secretName: users-service-kafka-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: microservices
spec:
  ports:
    - port: 3001
  selector:
    app: users-service